### ISSUE TITLE
App is down

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman-generator-list#17]
Heroku is returning a 500 when calling http://yeoman.io/generators/

I guess our latest update broke something.

@sindresorhus any chance you can look into it?

**Comment by SBoudrias** [comment]
I feel like I deployed this app to prod before, but I can't find it on heroku... Maybe I'm wrong and I never had the access. Anyway, this is making it hard to just access the log and see what's up.

But, my nose is telling me we're hitting Github API rate because we don't authenticate: https://github.com/yeoman/yeoman-generator-list/blob/master/index.js#L82-L86

Then, this is rejecting the promise, but we have no code handling errors in our data pipe: https://github.com/yeoman/yeoman-generator-list/blob/master/index.js#L114-L119

So that must just throw and we 500.

**Comment by addyosmani** [comment]
@SBoudrias I've just added you to the project on Heroku. You should have access. 

I have a feeling we might be hitting the unauthenticated rate limit too. Just did a redeploy and it unfortunately doesn't seem to have helped. 

Side: I can't remember if I brought this up before, but it feels like we should have some sort of worst-case fallback that just serves up a gh-pages cached version of the list from a monthly version of the list. This at least ensures that our end users never go without some sort of yeoman generator list available from the site.

**Comment by SBoudrias** [comment]
Looks like we're on it:

```
2015-04-30T08:08:50.813157+00:00 app[web.1]: GET / 500 1.060 ms - 22
2015-04-30T08:08:50.813323+00:00 app[web.1]: Error: GitHub fetch failed
2015-04-30T08:08:50.813328+00:00 app[web.1]:     at /app/index.js:93:20
2015-04-30T08:08:50.813329+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/gh-got/node_modules/got/index.js:177:4)
2015-04-30T08:08:50.813332+00:00 app[web.1]:     at ClientRequest.emit (events.js:107:17)
2015-04-30T08:08:50.813335+00:00 app[web.1]:     at TLSSocket.emit (events.js:129:20)
2015-04-30T08:08:50.813338+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-04-30T08:08:50.813337+00:00 app[web.1]:     at net.js:459:14
2015-04-30T08:08:50.813325+00:00 app[web.1]: GotError: Request to https://api.github.com/repos/soonick/generator-android-quality failed
2015-04-30T08:08:50.813327+00:00 app[web.1]: undefined
2015-04-30T08:08:50.813331+00:00 app[web.1]:     at ClientRequest.g (events.js:199:16)
2015-04-30T08:08:50.813334+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:271:9)
2015-04-30T08:08:52.361090+00:00 heroku[web.1]: Process running mem=554M(108.4%)
```

**Comment by SBoudrias** [comment]
Fixed the github authentication issue, but I still have these 500 errors in my log tails:

```
2015-04-30T08:20:32.313976+00:00 app[web.1]: GotError: Request to https://registry.npmjs.org/generator-iceddev/ failed
2015-04-30T08:20:32.313981+00:00 app[web.1]:     at ClientRequest.g (events.js:199:16)
2015-04-30T08:20:32.313818+00:00 app[web.1]: GET / 500 5.755 ms - 22
2015-04-30T08:20:32.313982+00:00 app[web.1]:     at ClientRequest.emit (events.js:107:17)
2015-04-30T08:20:32.313990+00:00 app[web.1]: Caused By: Error: socket hang up
2015-04-30T08:20:32.313992+00:00 app[web.1]:     at createHangUpError (_http_client.js:215:15)
2015-04-30T08:20:32.313993+00:00 app[web.1]:     at TLSSocket.socketOnEnd (_http_client.js:300:23)
2015-04-30T08:20:32.313995+00:00 app[web.1]:     at TLSSocket.emit (events.js:129:20)
2015-04-30T08:20:32.313979+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/package-json/node_modules/got/index.js:177:7)
2015-04-30T08:20:32.313996+00:00 app[web.1]:     at _stream_readable.js:908:16
2015-04-30T08:20:32.313998+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-04-30T08:20:32.318988+00:00 app[web.1]: GET / 500 1.165 ms - 22
2015-04-30T08:20:32.313985+00:00 app[web.1]:     at TLSSocket.emit (events.js:129:20)
2015-04-30T08:20:32.313987+00:00 app[web.1]:     at _stream_readable.js:908:16
2015-04-30T08:20:32.313989+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-04-30T08:20:32.313984+00:00 app[web.1]:     at TLSSocket.socketOnEnd (_http_client.js:300:9)
```

For anyone wanting to help with access to the app, just run `heroku logs --app yeoman-generator-list [--tail]`

**Comment by SevereOverfl0w** [comment]
> Side: I can't remember if I brought this up before, but it feels like we should have some sort of worst-case fallback that just serves up a gh-pages cached version of the list from a monthly version of the list. This at least ensures that our end users never go without some sort of yeoman generator list available from the site.


Or you could save a request, and use the "last known as good" list.

**Comment by SBoudrias** [comment]
Really weird, I can easily access the npm registry url the app is trying to fetch... I have a large amount of these error in the tailing, I'm wondering if maybe we've been spamming npm with requests... (like more request than the actual # users visiting that page)

**Comment by SBoudrias** [comment]
Need to sleep, so I'll leave it as it for now. At least there's no Github 500 anymore. We just need to figure out on the npm side.

**Comment by SBoudrias** [comment]
Actually, just reverted to the last known working version. That'll keep us in a working state while we figure out what went wrong.

**Comment by addyosmani** [comment]
Thanks for continuing to work on this, Simon. Get some sleep!

**Comment by SBoudrias** [comment]
@sindresorhus Hey, just pinging to see if you think you can fix the issue with the refactor?

**Comment by sindresorhus** [comment]
Agh, so typical. Sorry about the trouble. It ran fine for 24 hours so I foolishly assumed everything was fine.

I think the culprit is https://github.com/yeoman/yeoman-generator-list/commit/c8027e60d34916438e70f49b7333f1da8627cd61 I changed it to a personal access token for simplicity, but I forgot I have extra limits (this thing requires a LOT of requests...) on the `client_id`. So I think the fix is to just revert back to that for now. I'll look into it soon.

Though the real fix is #6.

**Comment by SBoudrias** [comment]
The app went down again today without any specific release. I'm unsure what went wrong here... But we should fix our latest version so it just work.

Reverted the token thingy hoping it'll just fix it, but we're still hitting 500 on prod and it's getting late here. I'd appreciate if anyone can take a look at it.

**Comment by SBoudrias** [comment]
This is fixed, and the docker version is now running on prod.
